FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get -y dist-upgrade

RUN apt-get -y --no-install-recommends install \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    doxygen \
    g++ \
    gdb \
    git \
    gnupg \
    gpg \
    less \
    libabsl-dev \
    libboost-all-dev \
    libgrpc++-dev \
    libprotobuf-dev \
    libssl-dev \
    libxtensor-dev \
    libusb-1.0-0-dev \
    libudev-dev \
    libgtk-3-dev \ 
    ninja-build \
    pkg-config \
    protobuf-compiler-grpc \
    software-properties-common \
    sudo \
    wget


RUN bash -c 'wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -'
RUN apt-add-repository -y 'deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main'
RUN apt-add-repository -y 'deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main'
RUN apt-get update

RUN apt-get -y --no-install-recommends install -t llvm-toolchain-bookworm-15 \
    clang-15 \
    clang-tidy-15

# Add repo to get cuda binaries
RUN sed -i 's/Components: main/Components: main contrib non-free non-free-firmware/g' /etc/apt/sources.list.d/debian.sources && \
    apt update && \
    apt -y install nvidia-cuda-dev nvidia-cuda-toolkit

# install appimage-builder
RUN apt install -y \
    binutils \
    coreutils \
    desktop-file-utils \
    fakeroot \
    fuse \
    libgdk-pixbuf2.0-dev \
    patchelf \
    python3-pip python3-setuptools \
    squashfs-tools \
    strace \
    vim \
    util-linux zsync

RUN pip3 install -U pip setuptools urllib3==1.26.12 requests==2.26.0 --break-system-packages

# install appimage-builder
RUN pip3 install --break-system-packages git+https://github.com/AppImageCrafters/appimage-builder.git@61c8ddde9ef44b85d7444bbe79d80b44a6a5576d

# install Go
RUN apt install -y golang-go 

# necessary library for jpeg
RUN apt install -y libturbojpeg-dev

# install GTest
RUN apt install -y libgtest-dev

# make workspace for building librealsense and viam-cpp-sdk
RUN mkdir -p /root/opt/src

# install librealsense from source
RUN cd /root/opt/src && \
    git clone https://github.com/IntelRealSense/librealsense.git && \
    cd librealsense && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_WITH_CUDA=true -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false && \
    make -j 4 && \
    make install -j 4 && \
    rm -rf /root/opt/src/librealsense

# install Viam C++ SDK from source frozen at a commit or tag
ENV PINNED_COMMIT_HASH="7f03834ca3be1b6964da37c865d9bd7439a9590f"
RUN cd /root/opt/src && \
    git clone https://github.com/viamrobotics/viam-cpp-sdk.git && \
    cd viam-cpp-sdk && \
    git checkout ${PINNED_COMMIT_HASH} && \
    mkdir build && \
    cd build && \
    cmake  \
    -DVIAMCPPSDK_BUILD_TESTS=OFF -DVIAMCPPSDK_BUILD_EXAMPLES=OFF \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DVIAMCPPSDK_USE_DYNAMIC_PROTOS=ON -DVIAMCPPSDK_OFFLINE_PROTO_GENERATION=ON \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    .. -G Ninja  && \
    ninja all -j 4 && \
    ninja install -j 4 && \
    rm -rf /root/opt/src/viam-cpp-sdk
