name: Build module.tar.gz and upload to registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            container:
              image: ghcr.io/viamrobotics/cpp-sdk-conan-ubuntu:jammy
            artifact-name: module-arm64
            platform: linux/arm64
          - os: ubuntu-22.04
            container:
              image: ghcr.io/viamrobotics/cpp-sdk-conan-ubuntu:jammy
            artifact-name: module-amd64
            platform: linux/amd64
          - os: macos-latest
            platform: darwin/arm64
            artifact-name: module-darwin-arm64
    container: ${{ matrix.container }}
    steps:
      - name: Set checkout ref (release)
        if: github.event_name == 'release'
        run: echo "CHECKOUT_REF=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set checkout ref (dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: echo "CHECKOUT_REF=${{ inputs.ref }}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}

      - name: Install conan (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja pkg-config conan
          conan profile detect || true
          conan remote add viamconan https://viam.jfrog.io/artifactory/api/conan/viamconan --index 0 --force

      - name: Build
        run: ./bin/build.sh

      - name: Upload module artifact
        if: github.event_name == 'release' || github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz

  upload:
    name: Upload modules to registry
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - artifact-name: module-arm64
            platform: linux/arm64
            artifact-path: ./artifacts/linux-arm64/
          - artifact-name: module-amd64
            platform: linux/amd64
            artifact-path: ./artifacts/linux-amd64/
          - artifact-name: module-darwin-arm64
            platform: darwin/arm64
            artifact-path: ./artifacts/darwin-arm64/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download module artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}

      - name: Upload module to registry
        uses: viamrobotics/upload-module@main
        with:
          meta-path: meta.json
          module-path: ${{ matrix.artifact-path }}/module.tar.gz
          platform: ${{ matrix.platform }}
          version: ${{ github.ref_name }}
          key-id: ${{ secrets.viam_key_id}}
          key-value: ${{ secrets.viam_key_value }}
