name: Build Integration Tests AppImage

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - 'integration/**'

permissions:
    pull-requests: write
    id-token: write

jobs:
  appimage:
    name: Integration Tests for RealSense
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: buildjet-8vcpu-ubuntu-2204-arm
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:arm64
              options: --platform linux/arm64
            make_target: integration-appimage-arm64
            arch: arm64
          - os: ubuntu-latest
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:amd64
              options: --platform linux/amd64
            make_target: integration-appimage-amd64
            arch: amd64

    container: ${{ matrix.container }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Integration Tests
      run: make ${{ matrix.make_target }}

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/385154741571/locations/global/workloadIdentityPools/viam-app-id/providers/github-provider-app'
        service_account: 'app-service@staging-cloud-web-app.iam.gserviceaccount.com'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.10.4
      with:
        headers: "cache-control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
