name: Build module.tar.gz and upload artifact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on

jobs:
  module:
    name: Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            container:
              image: debian:bullseye
            artifact-name: module-arm64
          - os: ubuntu-22.04
            container:
              image: debian:bullseye
            artifact-name: module-amd64

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Restore cached libraries
        uses: actions/cache@v3
        with:
          path: ~/.conan2
          key: ${{ matrix.os }}-conan-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            ${{ matrix.os }}-conan-

      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y dist-upgrade
          DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
              build-essential \
              ca-certificates \
              cmake \
              curl \
              doxygen \
              g++ \
              gdb \
              git \
              gnupg \
              gpg \
              less \
              libssl-dev \
              libudev-dev \
              ninja-build \
              software-properties-common \
              sudo \
              wget \
              zlib1g-dev

      - name: Update CMake for bullseye
        run: |
          sudo apt-get install -y software-properties-common
          apt-add-repository -y 'deb https://archive.debian.org/debian bullseye-backports main'

          apt-get update
          apt-get -y install cmake

          apt-get -y --no-install-recommends install -t bullseye-backports cmake

      - name: Setup python and conan
        run: |
          cat /etc/*-release
          ldd --version
          uname -a
          apt install -y python3-venv
          mkdir venv
          python3 -m venv ./venv
          . ./venv/bin/activate
          pip install conan
          conan profile detect

          echo '
          [replace_requires]
          openssl/*: openssl/system' >> ~/.conan2/profiles/default

          conan install -r conancenter --update --tool-requires=b2/5.3.1 --build=b2/5.3.1

      - name: Get librealsense
        run: |
          . ./venv/bin/activate
          git clone https://github.com/lia-viam/conan-center-index.git
          cd conan-center-index
          git checkout realsense-2.55.1
          conan create recipes/librealsense/all/conanfile.py --version=2.56.5 --build=missing

      - name: Get Viam SDK
        run: |
          . ./venv/bin/activate
          git clone https://github.com/viamrobotics/viam-cpp-sdk.git
          cd viam-cpp-sdk
          git checkout releases/v0.19.0
          conan create . -o "&:shared=False" --build=missing -s compiler.cppstd=17

      - name: Build
        run: |
          . ./venv/bin/activate
          conan create . --build=missing -o "viam-cpp-sdk/*:shared=False"
          conan install --requires=viam-camera-realsense/0.0.1 --deployer-package "&" -o "viam-cpp-sdk/*:shared=False" -v v

      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz
