name: Build module.tar.gz and upload artifact

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
        description: realsense module branch to run on

jobs:
  module:
    name: Intel RealSense module.tar.gz
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: buildjet-8vcpu-ubuntu-2204-arm
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:arm64
              options: --platform linux/arm64
            artifact-name: module-arm64
            platform: linux/arm64
          - os: ubuntu-latest
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:amd64
              options: --platform linux/amd64
            artifact-name: module-amd64
            platform: linux/amd64

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Setup python and conan
        run: |
          ldd --version
          apt install -y python3-venv
          mkdir venv
          python3 -m venv ./venv
          . ./venv/bin/activate
          pip install conan
          conan profile detect

      - name: Get librealsense
        run: |
          . ./venv/bin/activate
          git clone https://github.com/lia-viam/conan-center-index.git
          cd conan-center-index
          git checkout realsense-2.55.1
          conan create recipes/librealsense/all/conanfile.py --version=2.56.5 --build=missing

      - name: Get Viam SDK
        run: |
          . ./venv/bin/activate
          git clone https://github.com/viamrobotics/viam-cpp-sdk.git
          cd viam-cpp-sdk
          git checkout releases/v0.19.0
          conan create . -o "&:shared=False" --build=missing -s compiler.cppstd=17

      - name: Build
        run: |
          . ./venv/bin/activate
          conan create . --build=missing -o "viam-cpp-sdk/*:shared=False"
          conan install --requires=viam-camera-realsense/0.0.1 --deployer-package "&" -o "viam-cpp-sdk/*:shared=False" -v v

      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: module.tar.gz
